name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  nfc_manager:
  package_info_plus:
  provider:
  sqflite:
  url_launcher:
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.0.0
  flutter_barcode_scanner: ^2.0.0
  animated_text_kit: ^4.2.2
  qr_code_scanner: any
  splash_screen_view: ^3.0.0
  flutter_svg: ^0.22.0
  multiavatar: ^0.1.5
  badges: ^2.0.2
  awesome_dialog: ^3.0.1
  intl: ^0.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  firebase_auth: ^3.8.0
  firebase_core: ^1.22.0
  firebase_core_web: any
  cloud_firestore: ^3.4.8
  firebase_database: ^9.1.5


dev_dependencies:
  hive_generator: ^1.1.3
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:


flutter:
  uses-material-design: true
  assets:
    - splashscreen_image.png
    - lab_logo.png
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
